TECNOLOGIEDEMOCRATICHE_APP_ID: "provided by tecnologie democratiche"
TECNOLOGIEDEMOCRATICHE_APP_SECRET: "provided by tecnologie democratiche"
TECNOLOGIEDEMOCRATICHE_APP_URL: "https://tecnologiedemocratiche.herokuapp.com"
