default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: coorasse
  password:

development:
  <<: *default
  database: doorkeeper_example_development

test:
  <<: *default
  database: doorkeeper_example_test

production:
  <<: *default
  database: doorkeeper_example_production
